name: MSBuild

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build ARM64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /property:Platform=ARM64

    - name: Build x64 (AMD64)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /property:Platform=x64

    - name: Build x86 (Win32)
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /property:Platform=x86

    - name: Copy usb.ids, usbip_stub.inx and usbip_test.pfx
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cmd.exe /c copy /y D:\a\usbip-win\usbip-win\userspace\usb.ids D:\a\usbip-win\usbip-win\Release\ARM64\
        cmd.exe /c copy /y D:\a\usbip-win\usbip-win\userspace\usb.ids D:\a\usbip-win\usbip-win\Release\x64\
        cmd.exe /c copy /y D:\a\usbip-win\usbip-win\userspace\usb.ids D:\a\usbip-win\usbip-win\Release\Win32\
        cmd.exe /c copy /y D:\a\usbip-win\usbip-win\driver\stub\usbip_stub.inx D:\a\usbip-win\usbip-win\Release\ARM64\
        cmd.exe /c copy /y D:\a\usbip-win\usbip-win\driver\stub\usbip_stub.inx D:\a\usbip-win\usbip-win\Release\x64\
        cmd.exe /c copy /y D:\a\usbip-win\usbip-win\driver\stub\usbip_stub.inx D:\a\usbip-win\usbip-win\Release\Win32\
        curl.exe -L -O https://raw.githubusercontent.com/mbuilov/sed-windows/a8de79483710eb746ab4362aa4202115169a2848/sed-4.9-x64.exe
        .\sed-4.9-x64.exe -i 's/NTamd64/NTarm64/gi' D:\a\usbip-win\usbip-win\Release\ARM64\usbip_stub.inx
        .\sed-4.9-x64.exe -i 's/NTamd64/NTx86/gi' D:\a\usbip-win\usbip-win\Release\Win32\usbip_stub.inx
        cmd.exe /c del sed-4.9-x64.exe
        cmd.exe /c copy /y D:\a\usbip-win\usbip-win\driver\usbip_test.pfx D:\a\usbip-win\usbip-win\Release\

    - name: Cleaning Source Codes
      working-directory: ${{env.GITHUB_WORKSPACE}}
      continue-on-error: true
      run: |
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\attacher\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\libdrv\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbip\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbip_common\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbip_stub\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbip_vhci\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbip_vhci_ude\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbipd\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\attacher\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\libdrv\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbip\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbip_common\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbip_stub\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbip_vhci\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbip_vhci_ude\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbipd\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\Win32\attacher\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\Win32\libdrv\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\Win32\usbip\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\Win32\usbip_common\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\Win32\usbip_stub\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\Win32\usbip_vhci\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\Win32\usbip_vhci_ude\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\Win32\usbipd\

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: "usbip-win Release" 
        path: D:\a\usbip-win\usbip-win\Release\*
