name: MSBuild

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build ARM64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /property:Platform=ARM64

    - name: Build x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /property:Platform=x64

    - name: Build x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} /property:Platform=x86

    - name: Cleaning Source Codes
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\attacher\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\libdrv\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbip\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbip_common\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbip_stub\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbip_vhci\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbip_vhci_ude\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\ARM64\usbipd\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\attacher\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\libdrv\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbip\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbip_common\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbip_stub\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbip_vhci\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbip_vhci_ude\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x64\usbipd\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x86\attacher\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x86\libdrv\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x86\usbip\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x86\usbip_common\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x86\usbip_stub\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x86\usbip_vhci\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x86\usbip_vhci_ude\
        cmd.exe /c rd /s /q D:\a\usbip-win\usbip-win\Release\x86\usbipd\

    - name: Upload Artifact
      uses: actions/upload-artifact@master
      with:
        name: "usbip-win Release" 
        path: D:\a\usbip-win\usbip-win\Release\*
